
version: '3.7'
services:
  postgres:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=banco123
    ports:
      - '5432:5432'
    volumes:
      - ./postgres-data:/data/postgres
    networks:
      - link-net

  rabbitmq:
    image: rabbitmq:3.8-management-alpine
    container_name: "rabbitmq"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
      RABBITMQ_DEFAULT_VHOST: "local-vh"
    networks:
      - link-net
    ports:
      - "5672:5672"
      - "15672:15672"

networks:
  link-net:
    driver: bridge
